# This file contains the fastlane.tools configuration - BBL Modern Android App

output_dir="output/"
default_platform(:android)


platform :android do
  desc "Gradle Unit Test"
  lane :unit_test do
    gradle(task: "clean test",
    project_dir: './',
    print_command_output:true)
  end

  desc "Gradle Static Code Analysis"
  lane :SCA do
    gradle(task: "clean lint",
    project_dir: './',
    print_command_output:true)
  end

  desc "Build New Version"
  lane :build do |options|
    versionCode = options[:build_number]
    build_number = ENV['BUILD_NUMBER']
    puts versionCode
    gradle(task: "build -x test -x lint --info --stacktrace",
    project_dir: './',
    print_command_output:true,
    )
  end
  
  desc "Code Coverage"
  lane :code_coverage do
    gradle(task: "assemble$CONFIG testDebugUnitTest jacocoTestReport sonarqube",
    project_dir: 'source/',
    print_command_output:true
    )
  end
  
    # ------------------------ Upload Android build on Appcenter app
    lane :upload_to_appcenter do |options|
      build_number = ENV['BUILD_NUMBER']
      APPCENTER_API_TOKEN = ENV['APPCENTER_API_TOKEN']
      scm_change = options[:scm_change]
      appcenter_upload(
          api_token: APPCENTER_API_TOKEN,
          #api_token: "553f659a621e5fa1dcdfecb8132bc60ee8ae3ce8",
          owner_name: "ritjain2",
          app_name: "android-demo",
          apk: "./app/build/outputs/apk/debug/app-debug-#{build_number}.apk",
          destinations: "Collaborators",
          destination_type: "group",
          release_notes: scm_change,
          notify_testers: "true"
      )
    end
end
